name: Build All Examples
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build 2.1.1 Example
      working-directory: ./chapter-2/2.1.1/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.1.1 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.1.1
        path: ./chapter-2/2.1.1/build/singly-linked-list-insertion
    - name: Build 2.1.2 Example
      working-directory: ./chapter-2/2.1.2/
      run: mkdir build && cd build && cmake .. && make
    - name: Build 2.1.3 Example
      working-directory: ./chapter-2/2.1.3/
      run: mkdir build && cd build && cmake .. && make
    - name: Build 2.1.4 Example
      working-directory: ./chapter-2/2.1.4/
      run: mkdir build && cd build && cmake .. && make
    - name: Build 2.1.5 Example
      working-directory: ./chapter-2/2.1.5/
      run: mkdir build && cd build && cmake .. && make
    - name: Build 2.2.1 Example
      working-directory: ./chapter-2/2.2.1/
      run: mkdir build && cd build && cmake .. && make
    - name: Build 2.2.2 Example
      working-directory: ./chapter-2/2.2.2/
      run: mkdir build && cd build && cmake .. && make
    - name: Build 2.2.3 Example
      working-directory: ./chapter-2/2.2.3/
      run: mkdir build && cd build && cmake .. && make
