name: Build All Examples
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build 2.1.1 Example
      working-directory: ./chapter-2/2.1.1/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.1.1 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.1.1
        path: ./chapter-2/2.1.1/build/singly-linked-list-insertion
    - name: Build 2.1.2 Example
      working-directory: ./chapter-2/2.1.2/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.1.2 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.1.2
        path: ./chapter-2/2.1.2/build/singly-linked-list-searching
    - name: Build 2.1.3 Example
      working-directory: ./chapter-2/2.1.3/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.1.3 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.1.3
        path: ./chapter-2/2.1.3/build/singly-linked-list-deletion
    - name: Build 2.1.4 Example
      working-directory: ./chapter-2/2.1.4/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.1.4 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.1.4
        path: ./chapter-2/2.1.4/build/singly-linked-list-traversal
    - name: Build 2.1.5 Example
      working-directory: ./chapter-2/2.1.5/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.1.5 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.1.5
        path: ./chapter-2/2.1.5/build/singly-linked-list-inverse-traversal
    - name: Build 2.2.1 Example
      working-directory: ./chapter-2/2.2.1/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.2.1 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.2.1
        path: ./chapter-2/2.2.1/build/doubly-linked-list-insertion
    - name: Build 2.2.2 Example
      working-directory: ./chapter-2/2.2.2/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.2.2 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.2.2
        path: ./chapter-2/2.2.2/build/doubly-linked-list-deletion
    - name: Build 2.2.3 Example
      working-directory: ./chapter-2/2.2.3/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 2.2.3 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 2.2.3
        path: ./chapter-2/2.2.3/build/doubly-linked-list-traversal
    - name: Build 3.1 Example
      working-directory: ./chapter-3/3.1/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 3.1 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 3.1
        path: ./chapter-3/3.1/build/binary-search-tree-insertion
    - name: Build 3.2 Example
      working-directory: ./chapter-3/3.2/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 3.2 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 3.2
        path: ./chapter-3/3.2/build/binary-search-tree-searching
    - name: Build 3.3 Example
      working-directory: ./chapter-3/3.3/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 3.3 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 3.3
        path: ./chapter-3/3.3/build/binary-search-tree-deletion
    - name: Build 3.4 Example
      working-directory: ./chapter-3/3.4/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 3.4 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 3.4
        path: ./chapter-3/3.4/build/binary-search-tree-find-parent
    - name: Build 3.5 Example
      working-directory: ./chapter-3/3.5/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 3.5 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 3.5
        path: ./chapter-3/3.5/build/binary-search-tree-find-node
    - name: Build 3.6 Example
      working-directory: ./chapter-3/3.6/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 3.6 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 3.6
        path: ./chapter-3/3.6/build/binary-search-tree-min-max
    - name: Build 3.7 Example
      working-directory: ./chapter-3/3.7/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 3.7 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 3.7
        path: ./chapter-3/3.7/build/binary-search-tree-traversal
    - name: Build 4.1 Example
      working-directory: ./chapter-4/4.1/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 4.1 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 4.1
        path: ./chapter-4/4.1/build/heap-insertion
    - name: Build 4.2 Example
      working-directory: ./chapter-4/4.2/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 4.2 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 4.2
        path: ./chapter-4/4.2/build/heap-deletion
    - name: Build 4.3 Example
      working-directory: ./chapter-4/4.3/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 4.3 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 4.3
        path: ./chapter-4/4.3/build/heap-searching
    - name: Build 5 Example
      working-directory: ./chapter-5/5/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 5 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 5
        path: ./chapter-5/5/build/set-union-and-intersection
    - name: Build 7.1 Example
      working-directory: ./chapter-7/7.1/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 7.1 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 7.1
        path: ./chapter-7/7.1/build/avl-tree-insertion
    - name: Build 7.2 Example
      working-directory: ./chapter-7/7.2/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 7.2 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 7.2
        path: ./chapter-7/7.2/build/avl-tree-balancing
    - name: Build 7.3 Example
      working-directory: ./chapter-7/7.3/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 7.3 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 7.3
        path: ./chapter-7/7.3/build/avl-tree-insertion
    - name: Build 7.4 Example
      working-directory: ./chapter-7/7.4/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 7.4 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 7.4
        path: ./chapter-7/7.4/build/avl-tree-deletion
    - name: Build 8.1 Example
      working-directory: ./chapter-8/8.1/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 8.1 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 8.1
        path: ./chapter-8/8.1/build/bubble-sort
    - name: Build 8.2 Example
      working-directory: ./chapter-8/8.2/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 8.2 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 8.2
        path: ./chapter-8/8.2/build/merge-sort
    - name: Build 8.3 Example
      working-directory: ./chapter-8/8.3/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 8.3 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 8.3
        path: ./chapter-8/8.3/build/quick-sort
    - name: Build 8.4 Example
      working-directory: ./chapter-8/8.4/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 8.4 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 8.4
        path: ./chapter-8/8.4/build/insertion-sort
    - name: Build 8.5 Example
      working-directory: ./chapter-8/8.5/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 8.5 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 8.5
        path: ./chapter-8/8.5/build/shell-sort
    - name: Build 8.6 Example
      working-directory: ./chapter-8/8.6/
      run: mkdir build && cd build && cmake .. && make
    - name: Add 8.6 Example Artifact
      uses: actions/upload-artifact@v1
      with:
        name: 8.6
        path: ./chapter-8/8.6/build/radix-sort
