name: Build All Examples
on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build 2.1.1 Examples
      working-directory: ./chapter-2/2.2.1/
      run: mkdir build && cd build && cmake .. && make
      
